### ISSUE TITLE
Install script assigns wrong file permissions

### ISSUE THREAD

**Issue by jboonstra70** [PaesslerAG/PythonMiniProbe#1]
print "Changing File Permissions"
os.chmod('%s/probe.py' % probe_path, 755)
os.chmod('/etc/init.d/probe.sh', 755)
755 is interpreted as decimal and not octal as intended. Use 0755 (py2) or 0o755 (py3) or decimal 493

**Comment by konstantinpae** [comment]
solved with last commit. changed to 0755 as the intended target Python version is 2.7.x. In later versions full Python 3 compatibility is planned.
