### ISSUE TITLE
Error stating incompatible software versions between Probe and Core

### ISSUE THREAD

**Issue by ghost** [PaesslerAG/PythonMiniProbe#10]
I ran into trouble connecting a RPi (Raspbian Linux) to a PRTG Core server. The connection itself works, but the handshake seems to fail due to incompatible software versions.

Logfile output:

05/21/2015 11:51:59 - INFO - Starting new HTTPS connection (1): x.x.x.x
05/21/2015 11:52:05 - ERROR - ('Connection aborted.', BadStatusLine("\x01ctOK\xaf:F\xb7\x00\x00\x00\xa3\x00\x00\x00Handshake zwischen Probe und Core fehlgeschlagen! Inkompatible Softwareversionen von Probe und Core k\xf6nnten daf\xfcr verantwortlich sein. Bitte updaten Sie die Probe.\x01\x00\x00\x00\xff\xff\xff\xff\xd8\xbd\xda'-\x94\xe4@",))

Software versions:

PRTG Network Monitor 15.2.16.2229
PythonMiniProbe 15.2.2

Help would be much appreciated.

Best regards

**Comment by konstantinpae** [comment]
What port are you using to connect the mini probe? Please note that the same is connected to the web server but not the normal remote probe port. Could you change the port used in the probe.conf file?

**Comment by ghost** [comment]
Currently I am using port 23560 for the connection. The firewall on the PRTG Monitor system has no restrictions for outgoing traffic and a rule to allow TCP incoming on port 23560. The wget command stated in the installation instructions works fine but shows an error due to the fact that there is a self-signed certificate in place.

On the PRTG Monitor the value 23560 is set on "Port für Verbindungen mit Probes".

On the RPi he probe.conf looks like follows:

###Mini Probe Config File
protocol:1
name:Python MiniProbe
cleanmem:False
server:-deleted-
gid:-deleted-
baseinterval:60
subprocs:10
key:-deleted-
debug:True
port:23560
announced:0

The port could be easily changed of course. So your suggestion is to change the port on both ends?

**Comment by konstantinpae** [comment]
Ok, this explains the error message. The mini probes can only connect to the web interface of the PRTG core. Therefore it is neccessary the web interface runs secured with SSL. If this is the case, please change the line
port:23560
to 
port:443
(or any other web server port you are using). Afterwards the probe should connect.

**Comment by ghost** [comment]
Worked just fine, thanks a lot! Just to dispel my misconception: What is "Port für Verbindungen mit Probes" for then?

**Comment by konstantinpae** [comment]
You are welcome. Said port is for connections with "normal" remote probes which are running on Windows only. See the [PRTG manual](https://www.paessler.com/manuals/prtg/remote_probes_and_multiple_probes) for details.
