### ISSUE TITLE
Merge development to master branch

### ISSUE THREAD

**Issue by konstantinpae** [PaesslerAG/PythonMiniProbe#23]
I would like to merge the development branch to master. As date I would suggest next Tuesday, as  I'll be out of office from today evening. Would this be ok for you? @eagle00789

**Comment by eagle00789** [comment]
I'll do some more tests in the meantime, but next tuesday is fine with me

**Comment by konstantinpae** [comment]
Then I will close this issue for now. I'll let you know before merging. If you find any show stoppers, just let me know and I will delay the merge.
