### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by ghost** [PaesslerAG/PythonMiniProbe#26]
Hi,

just a short question: How do I cleanly uninstall the software from a (RPi) device?

Thanks in advance!

**Comment by eagle00789** [comment]
To manually remove the software,
delete the files:

```
    /etc/init.d/prtgprobe
    /etc/logrotate.d/prtgprobe
```

delete the folder

```
/probe
```

**Comment by konstantinpae** [comment]
Seems solved. Please reopen if necessary.
