### ISSUE TITLE
Reconnecting after prtg-server restart / unreachable

### ISSUE THREAD

**Issue by ghost** [PaesslerAG/PythonMiniProbe#41]
When the PRTG-Mainserver is unreachable (maybe for 20, 30 Seconds due a reboot after an update or so) the miniprobe disconnects and never reconnects. We have to manually restart all miniprobes. Is this an known issue?

**Comment by konstantinpae** [comment]
Yes, this is a known issue and should be fixed in the development branch.

**Comment by ghost** [comment]
HI Konstantin,

we will try this :-). Thank you!

**Comment by ghost** [comment]
Well, this worked fine. Just updatet all our miniprobes to the development version. They survived two restarts so far :-)

The miniprobe just doesnt wanted to start, until we created the "logs"-folder in "miniprobe". But maybe this was our error because we didnt re-run the probe-configuration.

Thank you! Keep up your great work, we really enjoy the possibility to monitor linux with prtg.
