### ISSUE TITLE
direct write access

### ISSUE THREAD

**Issue by eagle00789** [PaesslerAG/PythonMiniProbe#6]
since i am creating so many new features and fixes for the Python MiniProbe, i was wondering if i can get direct write access to the repository. it would make both our lives much easier since you just monitor my changes and my changes are directly available to everyone from the official repository.
I have many more features planned for the Python MiniProbe like:
snmp proxy (redirect a snmp request to another device on the remote network)
wmi proxy (same as above, but then for wmi)
and some others which i am still working out on paper...

**Comment by konstantinpae** [comment]
Sorry for the late answer was on sick leave.
Would it be possible discussing this via email directly? 
During my leave and yesterday we discussed some strategical stuff regarding the miniprobe (e.g. a deployment and testing process using travis ci, a git workflow, structural changes and so on) so I would   rather have this conversation via email than here. ;)
My direct email is konstantin (at) paessler dot com
