### ISSUE TITLE
snmpcustomsensor

### ISSUE THREAD

**Issue by stefanbrunner** [PaesslerAG/PythonMiniProbe#8]
Hallo

Der snmpcustomsensor funktioniert leider bei mir nicht wie gewünscht. 
Auf dem Core Server wird nur SNMP Rexuest failed angezeigt. Auf der Probe selber steht im log folgende Zeile: 05/13/2015 22:22:30 - ERROR - Ooops Something went wrong with 'mpsnmpcustom' sensor 2208. Error: NoSuchInstance instance has no attribute '**trunc**'
Der SNMP Tester liefert mir aber für die entsprechende OID einen Wert. Leider habe ich keine Kenntnisse in Python, dass ich es selber lösen könnte.
Danke für eine Antwort.

Freundliche Grüsse
Stefan Brunner

**Comment by eagle00789** [comment]
Could you please do the following for me to further analyse the problem.
Stop the prtgprobe service using:

```
sudo service prtgprobe stop
```

and start it again using the following command:

```
sudo python /probe/probe.py
```

Then make sure you have the SNMPCustomSensor added to your PRTG installation with the correct OID.
As soon as the SNMPCustomSensor is polled, it should print a traceback log. Please provide us with that traceback log.
Also, What device and OID are you trying to poll?
And last but not least, what is the value that the SNMP Tester returned for the OID?
As soon as you have the traceback log, you can stop the probe using CTRL + C and then starting the probe again using:

```
sudo service prtgprobe start
```

**Comment by stefanbrunner** [comment]
Problem is solved!
It wasn't the sensor, it was the device.
We monitor a QNAP NAS with the mini probe. The QNAP response a value as a string not as a integer!
To monitor a QNAP with the mini probe, the 9th value has to be count up by 1

e.g.
1.3.6.1.4.1.24681.1.2.11.1.3.3 response --> 31 C/87 F
1.3.6.1.4.1.24681.1.3.11.1.3.3 response --> 31
